-- PostgreSQL equivalent of the supplied SQL Server schema, for a NEW database.
-- Run manually; the application never creates tables or populates login/client.
BEGIN;

CREATE TABLE public.login (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL,
    password varchar(50)
);

CREATE TABLE public.client (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(50),
    address varchar(50),
    cups varchar(50) NOT NULL,
    id_login integer NOT NULL REFERENCES public.login(id)
);

CREATE TABLE public.invoice (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initial_date date NOT NULL,
    final_date date NOT NULL,
    tariff varchar(10) NOT NULL,
    id_client integer NOT NULL REFERENCES public.client(id),
    CONSTRAINT uq_invoice_client_period UNIQUE (id_client, initial_date, final_date),
    CONSTRAINT ck_invoice_period CHECK (initial_date <= final_date)
);

CREATE TABLE public.detail (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL,
    hour time(0) without time zone NOT NULL,
    consumption numeric(10, 1) NOT NULL,
    price numeric(17, 15) NOT NULL,
    cost_per_hour numeric(22, 20) NOT NULL,
    id_invoice integer NOT NULL REFERENCES public.invoice(id)
);

-- Local hours may repeat at daylight-saving transitions, so this is not unique.
CREATE INDEX ix_detail_invoice ON public.detail(id_invoice);
CREATE INDEX ix_client_login_cups ON public.client(id_login, cups);
CREATE INDEX ix_login_username ON public.login(username);

COMMIT;
